name: flutter_slidable
description: A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
version: 4.0.0
homepage: https://github.com/letsar/flutter_slidable

environment:
  sdk: '>=3.5.4 <4.0.0'
  flutter: "3.24.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  collection:

flutter:
